apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresdb-pv-volume
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"