apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresdb-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi