apiVersion: apps/v1
kind: Deployment
metadata:
  name: dream-vacation-frontend-deploy
  labels:
    app: frontend 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend 
  template:
    metadata:
      labels:
        app: frontend 
    spec:
      containers:
      - name: dream-vacation-frontend 
        image: theglad/dream-vacation-app-frontend:latest
        ports:
        - containerPort: 80  
        resources:
          requests:           
            cpu: "250m"
            memory: "64Mi"
          limits:
            cpu: "500m"
            memory: "128Mi"
        env:
        - name: REACT_APP_API_URL
          value: "http://dream-vacation-backend-svc.$(NAMESPACE).svc.cluster.local"
