apiVersion: v1
kind: Service
metadata:
  name: dream-vacation-frontend-svc
spec:
  type: LoadBalancer    
  selector:         
    app: frontend   
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80