name: Docker Build and K8s Minikube Deploy
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout code
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './backend/package-lock.json'
      - name: Install dependencies
        working-directory: ./backend
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: npm ci
      - name: Run tests
        working-directory: ./backend
        run: npm test -- --passWithNoTests

  build-image-and-push-to-dockerhub:
    needs: [ install-and-test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/dream-vacation-app-backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/dream-vacation-app-backend:${{ github.sha }}
      
      - name: Build and push with short SHA
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-5)
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/dream-vacation-app-backend:latest -t ${{ secrets.DOCKERHUB_USERNAME }}/dream-vacation-app-backend:$SHORT_SHA backend/
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/dream-vacation-app-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/dream-vacation-app-backend:$SHORT_SHA
 
  deploy:
    needs: [ build-image-and-push-to-dockerhub ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Start Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube start --driver=docker
          
      - name: Determine Namespace
        run: |
            if [[ $GITHUB_REF_NAME == 'develop' ]]; then
              NAMESPACE='dev'
            elif [[ $GITHUB_REF_NAME == 'main' ]]; then
              NAMESPACE='prod'
            else
              echo "Unknown branch, using default namespace 'default'"
              NAMESPACE='default'
            fi
            echo "NAMESPACE=$NAMESPACE" >> $GITHUB_ENV
        
      - name: Create Namespace
        run: |
            if [ -z "$NAMESPACE" ]; then
              echo "Error: Namespace is not set."
              exit 1
            fi
            kubectl create namespace $NAMESPACE --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy Database Resources
        run: |
          kubectl apply -f kubernetes-manifest/database/db-pv.yml -n $NAMESPACE
          kubectl apply -f kubernetes-manifest/database/db-pvc.yml -n $NAMESPACE
          kubectl apply -f kubernetes-manifest/database/db-secrets.yml -n $NAMESPACE
          kubectl apply -f kubernetes-manifest/database/db-cm.yml -n $NAMESPACE
          kubectl apply -f kubernetes-manifest/database/db-deployment.yml -n $NAMESPACE
          kubectl apply -f kubernetes-manifest/database/db-service.yml -n $NAMESPACE
  
      - name: Deploy Backend Application
        run: |
          kubectl apply -f kubernetes-manifest/backend/backend-cm.yml -n $NAMESPACE
          kubectl apply -f kubernetes-manifest/backend/backend-secrets.yml -n $NAMESPACE
          kubectl apply -f kubernetes-manifest/backend/backend-deployment.yml -n $NAMESPACE
          kubectl apply -f kubernetes-manifest/backend/backend-svc.yml -n $NAMESPACE

          kubectl get pods -n $NAMESPACE
          kubectl describe deployment dream-vacation-backend-deploy -n $NAMESPACE

          # Wait for deployments
          kubectl rollout status deployment/dream-vacation-backend-deploy -n $NAMESPACE --timeout=300s

          sleep 10
          
      - name: Get Minikube IP
        run: |
          echo "MINIKUBE_IP=$(minikube ip)" >> $GITHUB_ENV
          
      - name: Display Access URLs
        run: |
          NODE_PORT=$(kubectl get svc dream-vacation-backend-svc -n "$NAMESPACE" -o=jsonpath='{.spec.ports[0].nodePort}')
          echo "Frontend URL: http://$MINIKUBE_IP:$NODE_PORT"
